workflows:
  ios_build:
    name: iOS Build – OpenParsec
    max_build_duration: 120
    environment:
      xcode: latest
      ios_signing:
        distribution_type: development  # O 'ad_hoc', 'app_store'
        bundle_identifier: com.aigch.OpenParsec1  # Reemplaza con tu Bundle Identifier real
    scripts:
      - name: Install CocoaPods
        script: |
          if [ -f Podfile ]; then pod install; fi
      - name: Build Project
        script: |
          xcodebuild -workspace "project.xcworkspace" -scheme "OpenParsec" -configuration Release -sdk iphoneos
    artifacts:
      - build/ios/ipa/*.ipa
