workflows:
  ios_build:
    name: iOS Build – OpenParsec
    max_build_duration: 120
    environment:
      xcode: latest
    scripts:
      - name: Install CocoaPods
        script: |
          if [ -f Podfile ]; then pod install; fi
      - name: Build Project
        script: |
          xcodebuild -project "OpenParsec-main/OpenParsec-main/OpenParsec.xcodeproj" -scheme "OpenParsec" -configuration Release -sdk iphoneos
    artifacts:
      - build/ios/ipa/*.ipa
